/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/sRSMUkQjftg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function ContactForm() {
  return (
    (<div
      className="flex flex-col items-center justify-center min-h-screen p-8">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-bold">Connect with us for exciting opportunities in engineering field.</h1>
        <p className="text-muted-foreground">Reach out to us for internship placements, resume building, and more.</p>
      </div>
      
      <div className="mt-8 flex flex-col md:flex-row md:space-x-8">
        <div className="bg-[#f9f3eb] p-8 rounded-lg shadow-md">
          <form className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name">Contact Us</Label>
              <Input id="name" placeholder="Enter your full name here" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email*</Label>
              <Input id="email" placeholder="Enter your email address here" type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="message">Message*</Label>
              <Textarea
                id="message"
                placeholder="Enter your message here"
                className="min-h-[100px]" />
            </div>
            <Button className="bg-[#ff6b3c] text-white">Submit Form</Button>
          </form>
        </div>

        <div className="mt-8 md:mt-0 pt-8">
          <img
            src="https://images.unsplash.com/photo-1596526131083-e8c633c948d2?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
            alt="Example"
            className="rounded-lg shadow-md"
            width="600"
            height="400"
            style={{ aspectRatio: "500/300", objectFit: "cover" }} />
        </div>
      </div>
    </div>)
  );
}
