const cardData = [
    {
      title: 'Noteworthy technology acquisitions 2021',
      description: 'Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.',
      link: '#',
      bgColor: 'bg-blue-700',
      hoverBgColor: 'bg-blue-800',
      focusRingColor: 'focus:ring-blue-300',
      darkBgColor: 'dark:bg-blue-600',
      darkHoverBgColor: 'dark:hover:bg-blue-700',
      darkFocusRingColor: 'dark:focus:ring-blue-800',
    },
    {
      title: 'Technology Trends 2022',
      description: 'An overview of the key technology trends to watch out for in 2022.',
      link: '#',
      bgColor: 'bg-green-700',
      hoverBgColor: 'bg-green-800',
      focusRingColor: 'focus:ring-green-300',
      darkBgColor: 'dark:bg-green-600',
      darkHoverBgColor: 'dark:hover:bg-green-700',
      darkFocusRingColor: 'dark:focus:ring-green-800',
    },
    {
      title: 'Innovations in AI',
      description: 'A look at the latest innovations and advancements in artificial intelligence.',
      link: '#',
      bgColor: 'bg-purple-700',
      hoverBgColor: 'bg-purple-800',
      focusRingColor: 'focus:ring-purple-300',
      darkBgColor: 'dark:bg-purple-600',
      darkHoverBgColor: 'dark:hover:bg-purple-700',
      darkFocusRingColor: 'dark:focus:ring-purple-800',
    },
    {
      title: 'Future of Web Development',
      description: 'Exploring the future trends and technologies shaping web development.',
      link: '#',
      bgColor: 'bg-red-700',
      hoverBgColor: 'bg-red-800',
      focusRingColor: 'focus:ring-red-300',
      darkBgColor: 'dark:bg-red-600',
      darkHoverBgColor: 'dark:hover:bg-red-700',
      darkFocusRingColor: 'dark:focus:ring-red-800',
    },
    {
      title: 'Cloud Computing Advances',
      description: 'Key advancements in cloud computing and how they impact the industry.',
      link: '#',
      bgColor: 'bg-teal-700',
      hoverBgColor: 'bg-teal-800',
      focusRingColor: 'focus:ring-teal-300',
      darkBgColor: 'dark:bg-teal-600',
      darkHoverBgColor: 'dark:hover:bg-teal-700',
      darkFocusRingColor: 'dark:focus:ring-teal-800',
    },
    {
      title: 'Blockchain Revolution',
      description: 'Understanding the revolution in blockchain technology and its implications.',
      link: '#',
      bgColor: 'bg-indigo-700',
      hoverBgColor: 'bg-indigo-800',
      focusRingColor: 'focus:ring-indigo-300',
      darkBgColor: 'dark:bg-indigo-600',
      darkHoverBgColor: 'dark:hover:bg-indigo-700',
      darkFocusRingColor: 'dark:focus:ring-indigo-800',
    },
    {
      title: 'Cybersecurity Trends',
      description: 'The latest trends in cybersecurity and how to stay protected.',
      link: '#',
      bgColor: 'bg-yellow-700',
      hoverBgColor: 'bg-yellow-800',
      focusRingColor: 'focus:ring-yellow-300',
      darkBgColor: 'dark:bg-yellow-600',
      darkHoverBgColor: 'dark:hover:bg-yellow-700',
      darkFocusRingColor: 'dark:focus:ring-yellow-800',
    },
    {
      title: 'Big Data Analytics',
      description: 'How big data analytics is transforming industries and decision-making.',
      link: '#',
      bgColor: 'bg-orange-700',
      hoverBgColor: 'bg-orange-800',
      focusRingColor: 'focus:ring-orange-300',
      darkBgColor: 'dark:bg-orange-600',
      darkHoverBgColor: 'dark:hover:bg-orange-700',
      darkFocusRingColor: 'dark:focus:ring-orange-800',
    },
    {
      title: '5G Technology Impact',
      description: 'The impact of 5G technology on connectivity and the internet of things.',
      link: '#',
      bgColor: 'bg-pink-700',
      hoverBgColor: 'bg-pink-800',
      focusRingColor: 'focus:ring-pink-300',
      darkBgColor: 'dark:bg-pink-600',
      darkHoverBgColor: 'dark:hover:bg-pink-700',
      darkFocusRingColor: 'dark:focus:ring-pink-800',
    },
    {
      title: 'Augmented Reality Innovations',
      description: 'Exploring the latest innovations in augmented reality and their applications.',
      link: '#',
      bgColor: 'bg-gray-700',
      hoverBgColor: 'bg-gray-800',
      focusRingColor: 'focus:ring-gray-300',
      darkBgColor: 'dark:bg-gray-600',
      darkHoverBgColor: 'dark:hover:bg-gray-700',
      darkFocusRingColor: 'dark:focus:ring-gray-800',
    },
    {
      title: 'Virtual Reality Trends',
      description: 'The current trends and future directions of virtual reality technology.',
      link: '#',
      bgColor: 'bg-teal-800',
      hoverBgColor: 'bg-teal-900',
      focusRingColor: 'focus:ring-teal-400',
      darkBgColor: 'dark:bg-teal-700',
      darkHoverBgColor: 'dark:hover:bg-teal-800',
      darkFocusRingColor: 'dark:focus:ring-teal-900',
    },
    {
      title: 'IoT Innovations',
      description: 'Latest innovations in the Internet of Things and their impact on various industries.',
      link: '#',
      bgColor: 'bg-blue-800',
      hoverBgColor: 'bg-blue-900',
      focusRingColor: 'focus:ring-blue-400',
      darkBgColor: 'dark:bg-blue-700',
      darkHoverBgColor: 'dark:hover:bg-blue-800',
      darkFocusRingColor: 'dark:focus:ring-blue-900',
    },
    {
      title: 'Tech for Education',
      description: 'How technology is transforming education and learning environments.',
      link: '#',
      bgColor: 'bg-green-800',
      hoverBgColor: 'bg-green-900',
      focusRingColor: 'focus:ring-green-400',
      darkBgColor: 'dark:bg-green-700',
      darkHoverBgColor: 'dark:hover:bg-green-800',
      darkFocusRingColor: 'dark:focus:ring-green-900',
    },
    {
      title: 'Smart Home Technology',
      description: 'Advancements in smart home technology and their impact on daily life.',
      link: '#',
      bgColor: 'bg-red-800',
      hoverBgColor: 'bg-red-900',
      focusRingColor: 'focus:ring-red-400',
      darkBgColor: 'dark:bg-red-700',
      darkHoverBgColor: 'dark:hover:bg-red-800',
      darkFocusRingColor: 'dark:focus:ring-red-900',
    },
    {
      title: 'Tech Startups to Watch',
      description: 'The most promising tech startups to keep an eye on in the coming years.',
      link: '#',
      bgColor: 'bg-purple-800',
      hoverBgColor: 'bg-purple-900',
      focusRingColor: 'focus:ring-purple-400',
      darkBgColor: 'dark:bg-purple-700',
      darkHoverBgColor: 'dark:hover:bg-purple-800',
      darkFocusRingColor: 'dark:focus:ring-purple-900',
    },
    {
      title: 'Sustainable Tech Solutions',
      description: 'Exploring sustainable technology solutions and their benefits for the environment.',
      link: '#',
      bgColor: 'bg-yellow-800',
      hoverBgColor: 'bg-yellow-900',
      focusRingColor: 'focus:ring-yellow-400',
      darkBgColor: 'dark:bg-yellow-700',
      darkHoverBgColor: 'dark:hover:bg-yellow-800',
      darkFocusRingColor: 'dark:focus:ring-yellow-900',
    },
    {
      title: 'Tech Industry Challenges',
      description: 'Understanding the major challenges facing the tech industry today.',
      link: '#',
      bgColor: 'bg-orange-800',
      hoverBgColor: 'bg-orange-900',
      focusRingColor: 'focus:ring-orange-400',
      darkBgColor: 'dark:bg-orange-700',
      darkHoverBgColor: 'dark:hover:bg-orange-800',
      darkFocusRingColor: 'dark:focus:ring-orange-900',
    },
    {
      title: 'Tech for Healthcare',
      description: 'How technology is revolutionizing healthcare and medical services.',
      link: '#',
      bgColor: 'bg-pink-800',
      hoverBgColor: 'bg-pink-900',
      focusRingColor: 'focus:ring-pink-400',
      darkBgColor: 'dark:bg-pink-700',
      darkHoverBgColor: 'dark:hover:bg-pink-800',
      darkFocusRingColor: 'dark:focus:ring-pink-900',
    },
    {
      title: 'Digital Transformation',
      description: 'The impact of digital transformation on various business sectors.',
      link: '#',
      bgColor: 'bg-gray-800',
      hoverBgColor: 'bg-gray-900',
      focusRingColor: 'focus:ring-gray-400',
      darkBgColor: 'dark:bg-gray-700',
      darkHoverBgColor: 'dark:hover:bg-gray-800',
      darkFocusRingColor: 'dark:focus:ring-gray-900',
    },
    {
      title: 'Tech Innovations in Finance',
      description: 'Exploring the latest innovations in financial technology and services.',
      link: '#',
      bgColor: 'bg-teal-900',
      hoverBgColor: 'bg-teal-1000',
      focusRingColor: 'focus:ring-teal-500',
      darkBgColor: 'dark:bg-teal-800',
      darkHoverBgColor: 'dark:hover:bg-teal-900',
      darkFocusRingColor: 'dark:focus:ring-teal-1000',
    },
    {
      title: 'Digital Marketing Strategies',
      description: 'Effective digital marketing strategies and their impact on business growth.',
      link: '#',
      bgColor: 'bg-blue-900',
      hoverBgColor: 'bg-blue-1000',
      focusRingColor: 'focus:ring-blue-500',
      darkBgColor: 'dark:bg-blue-800',
      darkHoverBgColor: 'dark:hover:bg-blue-900',
      darkFocusRingColor: 'dark:focus:ring-blue-1000',
    },
    {
      title: 'Emerging Tech in Retail',
      description: 'The role of emerging technologies in transforming the retail industry.',
      link: '#',
      bgColor: 'bg-green-900',
      hoverBgColor: 'bg-green-1000',
      focusRingColor: 'focus:ring-green-500',
      darkBgColor: 'dark:bg-green-800',
      darkHoverBgColor: 'dark:hover:bg-green-900',
      darkFocusRingColor: 'dark:focus:ring-green-1000',
    },
    {
      title: 'Tech for Remote Work',
      description: 'How technology is enabling effective remote work and collaboration.',
      link: '#',
      bgColor: 'bg-red-900',
      hoverBgColor: 'bg-red-1000',
      focusRingColor: 'focus:ring-red-500',
      darkBgColor: 'dark:bg-red-800',
      darkHoverBgColor: 'dark:hover:bg-red-900',
      darkFocusRingColor: 'dark:focus:ring-red-1000',
    },
    {
      title: 'Advancements in Robotics',
      description: 'Latest advancements in robotics and their applications across industries.',
      link: '#',
      bgColor: 'bg-purple-900',
      hoverBgColor: 'bg-purple-1000',
      focusRingColor: 'focus:ring-purple-500',
      darkBgColor: 'dark:bg-purple-800',
      darkHoverBgColor: 'dark:hover:bg-purple-900',
      darkFocusRingColor: 'dark:focus:ring-purple-1000',
    },
    {
      title: 'Tech for Smart Cities',
      description: 'Exploring the role of technology in developing smart cities and urban solutions.',
      link: '#',
      bgColor: 'bg-yellow-900',
      hoverBgColor: 'bg-yellow-1000',
      focusRingColor: 'focus:ring-yellow-500',
      darkBgColor: 'dark:bg-yellow-800',
      darkHoverBgColor: 'dark:hover:bg-yellow-900',
      darkFocusRingColor: 'dark:focus:ring-yellow-1000',
    },
  ];
  
  export default cardData;
  